title: Portfolio
description: A showcase of my tech art and rendering projects
theme: null

# Plugins (GitHub Pages defaults, safe to include)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Optional: to show up on GitHub
show_downloads: false

# kramdown
markdown: kramdown
kramdown:
  parse_block_html: true

# Custom navigation links
navigation:
  - name: Home
    link: /
  - name: 3D Art
    link: /3d-art.html
  - name: Tech Art
    link: /tech-art.html
  - name: Computer Graphics
    link: /computer-graphics.html