title: Portfolio
description: A showcase of my tech art and rendering projects
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Optional: to show up on GitHub
show_downloads: false

# Custom navigation links
navigation:
  - name: 3D Art
    link: /3d-art/
  - name: Tech Art
    link: /tech-art/
  - name: Computer Graphics
    link: /computer-graphics/
